apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: elasticsearch7
  name: elasticsearch7
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: elasticsearch7
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: elasticsearch7
    spec:
      initContainers:
        - name: increase-the-vm-max-map-count
          image: {{ required "Missing value ES5_BUSY_IMAGE" .Values.ES5_BUSY_IMAGE }}
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: fix-rights
          image: {{ required "Missing value ES5_BUSY_IMAGE" .Values.ES5_BUSY_IMAGE }}
          command:
            - /bin/chmod
            - "777"
            - /usr/share/elasticsearch/data
          volumeMounts:
          - name: elasticsearch7-claim0
            mountPath: "/usr/share/elasticsearch/data"
          securityContext:
            privileged: true
      containers:
      - env:
        - name: cluster.name
          value: {{ required "Missing value FDK_ES_CLUSTERNAME" .Values.FDK_ES_CLUSTERNAME }}
        - name: xpack.security.enabled
          value: {{ required "Missing value FDK_ES_SECURITY"  .Values.FDK_ES_SECURITY | quote}}
        - name: cluster.initial_master_nodes
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: {{ required "Missing value ES7_IMAGE" .Values.ES7_IMAGE }}
        imagePullPolicy: Always
        name: elasticsearch7
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          requests:
            memory: {{ required "Missing value FDK_ES_MEMORY" .Values.FDK_ES_MEMORY | quote }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch7-claim0
      restartPolicy: Always
      volumes:
      - name: elasticsearch7-claim0
        persistentVolumeClaim:
          claimName: elasticsearch7-claim0
status: {}